<?php


namespace PhpTutorial\test\stringTests;


use PhpTutorial\tasks\StringTask;
use PHPUnit\Framework\TestCase;

class StringBase extends TestCase
{
    /**
     * @var StringTask
     */
    protected $stringTask;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->stringTask = new StringTask();
    }


}